export { default as ModalStack } from './ModalStack.svelte'
export { getModal, onBeforeClose, default as ModalContext } from './ModalContext.svelte'
export * from './modal.svelte'
export * from './modals.svelte'
export type { LazyModalComponent, ModalComponent } from './types.d.ts'
