export { default as Modals, modals, type ModalsProps } from './Modals.svelte'
export { getModal, onBeforeClose } from './ModalContext.svelte'
export * from './modal.svelte'
export * from './modals-context.svelte'
export type { LazyModalComponent, ModalComponent } from './types.d.ts'
