export { default as Modals } from './Modals.svelte'
export { getModal } from './ModalContext.svelte'
export * from './modal-stack.svelte'
export * from './stacked-modal.svelte'
export type { CloseProp, LazyModalComponent, ModalComponent } from './types.d.ts'
